#Paffs
import os
from cmath import isnan

Import('envGlobal')

print("PAFFS")

envGlobal.Append(CPPPATH=[os.path.abspath('.')])

envGlobal.SConscript([
	os.path.join('$OUTPOST_CORE_PATH', 'modules/SConscript.library'),
	], exports='envGlobal')

envGlobal.Append(CPPPATH=[
	os.path.join(os.path.abspath("./config/"), '$PAFFSCONFIG')
])

if not envGlobal['PAFFSCONFIG']:
	print('No configuration set!')
else:
	print('Paffs configuration: ' + str(envGlobal['PAFFSCONFIG']))

env = envGlobal.Clone()

files  = env.Glob('*.cpp')

library = env.StaticLibrary('paffs', files)

envGlobal.Append(LIBS=[
	'paffs',
	'outpost_rtos',
	'outpost_time',
])

envGlobal.Install('$BUILDPATH/lib', library)
