#test build
import os

rootpath = Dir('../../../').abspath
extpath = os.path.join(rootpath, 'ext')
outpost_core_path = os.path.join(extpath, 'outpost-core')

print("UNITTESTS")

envGlobal = Environment(toolpath=[os.path.join(extpath, 'scons-build-tools/site_tools')],
                        tools=['utils_buildformat'],
                        BASEPATH=os.path.abspath('.'),
                        ENV=os.environ)

buildfolder = os.path.join(rootpath, 'release')
envGlobal['CCFLAGS_optimize'] = ['-O2']
envGlobal.Tool('compiler_hosted_gcc')
envGlobal.Tool('settings_buildpath')
envGlobal['BUILDPATH'] = os.path.abspath(buildfolder)
envGlobal['ROOTPATH'] = rootpath
envGlobal['OUTPOST_CORE_PATH'] = outpost_core_path
envGlobal['CXXFLAGS_language'] = ['-std=c++11']

envGlobal.SConscript([
    os.path.join(rootpath, 'ds/paffs/SConscript'),
    os.path.join(outpost_core_path, 'modules/SConscript.test'),
    ],
	exports='envGlobal'
)

env = envGlobal.Clone()

env.Append(LIBS=[
	'simuDriver',
])
env.Append(CCFLAGS_target = [
	'-v'
])

files  = Glob('*.cpp')

print("Libs von UNITTEST: " + str(env['LIBS']))
program = env.Program('unittests', files)

#install = env.Install('$BUILDPATH', program)
envGlobal.Alias('test', program)
envGlobal.Default('test')