#Paffs
import os
from cmath import isnan

Import('envGlobal')

print("PAFFS")

envGlobal.Append(CPPPATH=[os.path.abspath('.')])

envGlobal.SConscript([
	os.path.join('$OUTPOST_CORE_PATH', 'modules/SConscript.library'),
	], exports='envGlobal')

#TODO: Move config from Lib to user 
envGlobal.Append(CPPPATH=[
	os.path.join(os.path.abspath("./config/"), '$PAFFSCONFIG')
])

envGlobal.Append(LIBS=[
	'paffs',
	'outpost_rtos',
	'outpost_time',
])

#intentionally not using clone because if we chose Simu driver,
# it will choose its own config

files  = envGlobal.Glob('*.cpp')

#for file in files:
#    print (file)

library = envGlobal.StaticLibrary('paffs', files)

envGlobal.Install('$BUILDPATH/lib', library)
