#Paffs
import os
from cmath import isnan

Import('envGlobal')

print("PAFFS")

envGlobal.Append(CPPPATH=[os.path.abspath('.')])

envGlobal.SConscript([
	os.path.join('$OUTPOST_CORE_PATH', 'modules/SConscript.library'),
	], exports='envGlobal')

envGlobal.Append(LIBS=[
	'paffs',
	'outpost_rtos',
	'outpost_time',
])

env = envGlobal.Clone()

files  = env.Glob('*.cpp')

#for file in files:
#    print (file)

library = env.StaticLibrary('paffs', files)

envGlobal.Install('$BUILDPATH/lib', library)
