#Paffs drivers
import os

Import('envGlobal')

print("SIMUDRIVER")

envGlobal.Append(LIBS=[
	'simu'
])

env = envGlobal.Clone()

files  = env.Glob('simu.cpp')

library = env.StaticLibrary('simuDriver', files)

envGlobal.Install('$BUILDPATH/lib', library)

print("NULLDRIVER")

env = envGlobal.Clone()

files  = env.Glob('null.cpp')

library = env.StaticLibrary('nullDriver', files)

envGlobal.Append(LIBS=[
])
envGlobal.Install('$BUILDPATH/lib', library)
