#Paffs Simudriver
import os

Import('envGlobal')

print("SIMUDRIVER")

#envGlobal.Append(CPPPATH=[os.path.abspath('.')])

env = envGlobal.Clone()

files  = env.Glob('*.cpp')

library = env.StaticLibrary('simuDriver', files)

envGlobal.Append(LIBS=[
	'simuDriver',
	'simu'
])
envGlobal.Install('$BUILDPATH/lib', library)
